-- AlterEnum
ALTER TYPE "EmailNotificationType" ADD VALUE 'BUSINESS_SPEND_CARD_ISSUED';
ALTER TYPE "EmailNotificationType" ADD VALUE 'BUSINESS_SPEND_CARD_ACTIVATED';
ALTER TYPE "EmailNotificationType" ADD VALUE 'BUSINESS_SPEND_CARD_SUSPENDED';
ALTER TYPE "EmailNotificationType" ADD VALUE 'BUSINESS_SPEND_CARD_TERMINATED';
