-- AlterEnum
ALTER TYPE "KycRequiredService" ADD VALUE 'BUSINESS_SPEND_CARD';

-- AlterEnum
ALTER TYPE "PricingServiceType" ADD VALUE 'BUSINESS_SPEND_CARD_CREATE';
ALTER TYPE "PricingServiceType" ADD VALUE 'BUSINESS_SPEND_CARD_FUND';
ALTER TYPE "PricingServiceType" ADD VALUE 'BUSINESS_SPEND_CARD_WITHDRAW';
ALTER TYPE "PricingServiceType" ADD VALUE 'BUSINESS_SPEND_CARD_TERMINATE';
ALTER TYPE "PricingServiceType" ADD VALUE 'BUSINESS_SPEND_CARD_ACTIVATE';
ALTER TYPE "PricingServiceType" ADD VALUE 'BUSINESS_SPEND_CARD_SUSPEND';
ALTER TYPE "PricingServiceType" ADD VALUE 'BUSINESS_SPEND_CARD_PIN_UPDATE';
ALTER TYPE "PricingServiceType" ADD VALUE 'BUSINESS_SPEND_CARD_LIMITS_UPDATE';
