import crypto from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Client } from "pg";
import { PrismaClient } from "@prisma/client";
import type { PrismaClient as PrismaClientType } from "@prisma/client";
import { env } from "../../config/env.js";
import logger from "../../lib/logger.js";

const execFileAsync = promisify(execFile);

/**
 * Internal-only database name format: demo_<32 hex chars>. Never accept a database name from a
 * request — this regex is the gate every CREATE/DROP call must pass before touching Postgres.
 */
export const DEMO_DB_NAME_REGEX = /^demo_[0-9a-f]{32}$/;

function parseDatabaseNameFromUrl(databaseUrl: string): string {
  const url = new URL(databaseUrl);
  return url.pathname.replace(/^\//, "");
}

const PROD_DATABASE_NAME = parseDatabaseNameFromUrl(env.DATABASE_URL);

/** Generates a new, internally-random demo database name. Never derived from any client input. */
export function generateDemoDatabaseName(): string {
  return `demo_${crypto.randomBytes(16).toString("hex")}`;
}

/**
 * Validates a database name is safe to CREATE/DROP: matches the internal-only naming scheme,
 * and can never equal the production database (belt-and-braces alongside the regex, since the
 * prod name could theoretically collide in format if this prefix were ever reused there).
 */
export function assertSafeDemoDatabaseName(name: string): void {
  if (!DEMO_DB_NAME_REGEX.test(name)) {
    throw new Error(`Refusing to operate on database name that fails the demo naming pattern: ${name}`);
  }
  if (name === PROD_DATABASE_NAME) {
    throw new Error("Refusing to operate on the production database");
  }
}

function buildDemoDatabaseUrl(databaseName: string): string {
  const url = new URL(env.DATABASE_URL);
  url.pathname = `/${databaseName}`;
  return url.toString();
}

/** Connects to the Postgres server's maintenance database (same server/credentials as DATABASE_URL, just not the app's own database) to run CREATE/DROP DATABASE, which cannot run against the database currently in use. */
async function withMaintenanceConnection<T>(fn: (client: Client) => Promise<T>): Promise<T> {
  const url = new URL(env.DATABASE_URL);
  url.pathname = "/postgres";
  const client = new Client({ connectionString: url.toString() });
  await client.connect();
  try {
    return await fn(client);
  } finally {
    await client.end();
  }
}

/** Creates a new, empty, isolated Postgres database for a demo session and runs migrations against it. Callers must pass a name generated by generateDemoDatabaseName() — never client input. */
export async function provisionDemoDatabase(databaseName: string): Promise<void> {
  assertSafeDemoDatabaseName(databaseName);

  await withMaintenanceConnection(async (client) => {
    // Identifiers can't be parameterized — safe here only because assertSafeDemoDatabaseName
    // above already restricted `databaseName` to /^demo_[0-9a-f]{32}$/.
    await client.query(`CREATE DATABASE "${databaseName}"`);
  });

  await runMigrationsAgainst(databaseName);
  logger.info({ demoDatabase: databaseName }, "demo.database.provisioned");
}

/** Runs `prisma migrate deploy` against the given demo database so its schema matches production. */
async function runMigrationsAgainst(databaseName: string): Promise<void> {
  const apiDir = fileURLToPath(new URL("../../../", import.meta.url)); // src/modules/demo -> apps/api
  const prismaBin = path.join(apiDir, "node_modules", ".bin", "prisma");
  const databaseUrl = buildDemoDatabaseUrl(databaseName);
  await execFileAsync(prismaBin, ["migrate", "deploy"], {
    cwd: apiDir,
    env: { ...process.env, DATABASE_URL: databaseUrl },
  });
}

/** Drops an isolated demo database. Only ever called after the caller has verified `databaseName` is a real DemoSession.databaseName from the DB — see demoCleanup.service.ts. */
export async function dropDemoDatabase(databaseName: string): Promise<void> {
  assertSafeDemoDatabaseName(databaseName);
  evictDemoPrismaClient(databaseName);
  await withMaintenanceConnection(async (client) => {
    // Terminate any lingering connections first — DROP DATABASE fails while sessions are open.
    await client.query(
      `SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()`,
      [databaseName],
    );
    await client.query(`DROP DATABASE IF EXISTS "${databaseName}"`);
  });
  logger.info({ demoDatabase: databaseName }, "demo.database.dropped");
}

// ── Dynamic Prisma client cache ─────────────────────────────────────────
// Keyed by database name. Idle-evicted so many short-lived demo sessions never accumulate open
// connections against the app's singleton connection budget. Never merged into app.prisma.

type CacheEntry = { client: PrismaClientType; lastUsedAt: number };
const clientCache = new Map<string, CacheEntry>();
const IDLE_EVICTION_MS = 10 * 60 * 1000; // 10 minutes unused
const MAX_CACHED_CLIENTS = 50;

let evictionTimer: NodeJS.Timeout | undefined;

function ensureEvictionTimer(): void {
  if (evictionTimer) return;
  evictionTimer = setInterval(() => {
    const now = Date.now();
    for (const [name, entry] of clientCache.entries()) {
      if (now - entry.lastUsedAt > IDLE_EVICTION_MS) {
        evictDemoPrismaClient(name);
      }
    }
  }, 60 * 1000);
  evictionTimer.unref();
}

export function getDemoPrismaClient(databaseName: string): PrismaClientType {
  assertSafeDemoDatabaseName(databaseName);
  ensureEvictionTimer();
  const existing = clientCache.get(databaseName);
  if (existing) {
    existing.lastUsedAt = Date.now();
    return existing.client;
  }
  if (clientCache.size >= MAX_CACHED_CLIENTS) {
    // Evict the least-recently-used entry to make room rather than let the cache grow unbounded.
    let oldestKey: string | undefined;
    let oldestAt = Infinity;
    for (const [name, entry] of clientCache.entries()) {
      if (entry.lastUsedAt < oldestAt) {
        oldestAt = entry.lastUsedAt;
        oldestKey = name;
      }
    }
    if (oldestKey) evictDemoPrismaClient(oldestKey);
  }
  const client = new PrismaClient({ datasources: { db: { url: buildDemoDatabaseUrl(databaseName) } } });
  clientCache.set(databaseName, { client, lastUsedAt: Date.now() });
  return client;
}

export function evictDemoPrismaClient(databaseName: string): void {
  const entry = clientCache.get(databaseName);
  if (!entry) return;
  clientCache.delete(databaseName);
  void entry.client.$disconnect();
}

/** Test/shutdown helper — disconnects and clears every cached demo client. */
export async function disconnectAllDemoPrismaClients(): Promise<void> {
  const entries = [...clientCache.values()];
  clientCache.clear();
  if (evictionTimer) {
    clearInterval(evictionTimer);
    evictionTimer = undefined;
  }
  await Promise.all(entries.map((e) => e.client.$disconnect()));
}
