import type { FastifyInstance } from "fastify";
import type { ZodTypeProvider } from "fastify-type-provider-zod";
import { z } from "zod";
import { requirePermission, requireStaffAuth } from "../../middleware/requireStaffAuth.js";
import { decryptCredential, encryptCredential } from "../../lib/credentialEncryption.js";

const SETTINGS_KEY = "authentication-integrations";
const settingsSchema = z.object({
  apple: z.object({ enabled: z.boolean(), clientId: z.string(), teamId: z.string(), keyId: z.string(), privateKey: z.string().optional() }),
  facebook: z.object({ enabled: z.boolean(), clientId: z.string(), clientSecret: z.string().optional() }),
  twitter: z.object({ enabled: z.boolean(), clientId: z.string(), clientSecret: z.string().optional() }),
  passkeys: z.object({ enabled: z.boolean(), rpId: z.string(), rpName: z.string() }),
});
type Settings = z.infer<typeof settingsSchema>;
const empty: Settings = {
  apple: { enabled: false, clientId: "", teamId: "", keyId: "" },
  facebook: { enabled: false, clientId: "" },
  twitter: { enabled: false, clientId: "" },
  passkeys: { enabled: true, rpId: "", rpName: "" },
};

function safe(value: Settings) {
  return {
    ...value,
    apple: { ...value.apple, privateKey: undefined, privateKeyConfigured: Boolean(value.apple.privateKey) },
    facebook: { ...value.facebook, clientSecret: undefined, clientSecretConfigured: Boolean(value.facebook.clientSecret) },
    twitter: { ...value.twitter, clientSecret: undefined, clientSecretConfigured: Boolean(value.twitter.clientSecret) },
  };
}

export async function integrationsRoutes(app: FastifyInstance) {
  const server = app.withTypeProvider<ZodTypeProvider>();
  // Prisma Client is regenerated by the deployment migration. Keep the API build compatible
  // with an already-generated client while this new migration is pending locally.
  const db = app.prisma as typeof app.prisma & { secureSetting: any; adminAuditLog: any };
  server.get("/admin/settings/authentication", { preHandler: requireStaffAuth }, async (_request, reply) => {
    const record = await db.secureSetting.findUnique({ where: { key: SETTINGS_KEY } });
    if (!record) return reply.send(safe(empty));
    return reply.send(safe(settingsSchema.parse(JSON.parse(decryptCredential(record.encryptedValue)))));
  });

  server.put("/admin/settings/authentication", { preHandler: [requireStaffAuth, requirePermission("api_keys.manage")], schema: { body: settingsSchema } }, async (request, reply) => {
    const prior = await db.secureSetting.findUnique({ where: { key: SETTINGS_KEY } });
    const old = prior ? settingsSchema.parse(JSON.parse(decryptCredential(prior.encryptedValue))) : empty;
    // Omitted secret fields preserve their prior encrypted values; the UI never receives them.
    const next: Settings = {
      ...request.body,
      apple: { ...request.body.apple, privateKey: request.body.apple.privateKey || old.apple.privateKey },
      facebook: { ...request.body.facebook, clientSecret: request.body.facebook.clientSecret || old.facebook.clientSecret },
      twitter: { ...request.body.twitter, clientSecret: request.body.twitter.clientSecret || old.twitter.clientSecret },
    };
    await app.prisma.$transaction([
      db.secureSetting.upsert({ where: { key: SETTINGS_KEY }, create: { key: SETTINGS_KEY, encryptedValue: encryptCredential(JSON.stringify(next)), updatedById: request.staffUser!.sub }, update: { encryptedValue: encryptCredential(JSON.stringify(next)), updatedById: request.staffUser!.sub } }),
      db.adminAuditLog.create({ data: { actorId: request.staffUser!.sub, action: "authentication_settings.updated", target: SETTINGS_KEY } }),
    ]);
    return reply.send(safe(next));
  });
}
