import type { FastifyInstance } from "fastify";
import type { ZodTypeProvider } from "fastify-type-provider-zod";
import { z } from "zod";
import { requirePermission, requireStaffAuth } from "../../middleware/requireStaffAuth.js";
import { decryptCredential, encryptCredential } from "../../lib/credentialEncryption.js";
import { applyIntegrationSettings, type IntegrationSettings } from "../../lib/integrationRuntimeConfig.js";
import { env } from "../../config/env.js";

const SETTINGS_KEY = "platform-integrations";

const settingsSchema = z.object({
  yativo: z.object({
    mode: z.enum(["mock", "sandbox", "live"]),
    fiatBaseUrl: z.string().url(),
    cryptoBaseUrl: z.string().url(),
    kycBaseUrl: z.string().url(),
    apiKey: z.string().optional().default(""),
    apiSecret: z.string().optional().default(""),
    webhookSecret: z.string().optional().default(""),
  }),
  smtp: z.object({
    host: z.string().optional().default(""),
    port: z.coerce.number().default(587),
    secure: z.boolean().default(false),
    user: z.string().optional().default(""),
    password: z.string().optional().default(""),
    fromAddress: z.string().default("no-reply@example.com"),
  }),
});
type Settings = z.infer<typeof settingsSchema>;

/** What the process is actually running on right now, used whenever no row has been saved to the DB yet. */
const envDefaults: Settings = {
  yativo: {
    mode: env.YATIVO_MODE,
    fiatBaseUrl: env.YATIVO_FIAT_BASE_URL,
    cryptoBaseUrl: env.YATIVO_CRYPTO_BASE_URL,
    kycBaseUrl: env.YATIVO_KYC_BASE_URL,
    apiKey: env.YATIVO_API_KEY,
    apiSecret: env.YATIVO_API_SECRET,
    webhookSecret: env.YATIVO_WEBHOOK_SECRET,
  },
  smtp: {
    host: env.SMTP_HOST ?? "",
    port: env.SMTP_PORT,
    secure: env.SMTP_SECURE,
    user: env.SMTP_USER ?? "",
    password: env.SMTP_PASSWORD ?? "",
    fromAddress: env.EMAIL_FROM_ADDRESS,
  },
};

function safe(value: Settings) {
  return {
    yativo: {
      ...value.yativo,
      apiKey: undefined,
      apiKeyConfigured: Boolean(value.yativo.apiKey),
      apiSecret: undefined,
      apiSecretConfigured: Boolean(value.yativo.apiSecret),
      webhookSecret: undefined,
      webhookSecretConfigured: Boolean(value.yativo.webhookSecret),
    },
    smtp: {
      ...value.smtp,
      password: undefined,
      passwordConfigured: Boolean(value.smtp.password),
    },
  };
}

export async function platformIntegrationsRoutes(app: FastifyInstance) {
  const server = app.withTypeProvider<ZodTypeProvider>();
  // Prisma Client is regenerated by the deployment migration. Keep the API build compatible
  // with an already-generated client while this new migration is pending locally.
  const db = app.prisma as typeof app.prisma & { secureSetting: any; adminAuditLog: any };

  server.get("/admin/settings/integrations", { preHandler: requireStaffAuth }, async (_request, reply) => {
    const record = await db.secureSetting.findUnique({ where: { key: SETTINGS_KEY } });
    if (!record) return reply.send(safe(envDefaults));
    return reply.send(safe(settingsSchema.parse(JSON.parse(decryptCredential(record.encryptedValue)))));
  });

  server.put(
    "/admin/settings/integrations",
    { preHandler: [requireStaffAuth, requirePermission("api_keys.manage")], schema: { body: settingsSchema } },
    async (request, reply) => {
      const prior = await db.secureSetting.findUnique({ where: { key: SETTINGS_KEY } });
      const old = prior ? settingsSchema.parse(JSON.parse(decryptCredential(prior.encryptedValue))) : envDefaults;
      // Omitted secret fields preserve their prior value; the UI never receives them.
      const next: Settings = {
        yativo: {
          ...request.body.yativo,
          apiKey: request.body.yativo.apiKey || old.yativo.apiKey,
          apiSecret: request.body.yativo.apiSecret || old.yativo.apiSecret,
          webhookSecret: request.body.yativo.webhookSecret || old.yativo.webhookSecret,
        },
        smtp: {
          ...request.body.smtp,
          password: request.body.smtp.password || old.smtp.password,
        },
      };
      await app.prisma.$transaction([
        db.secureSetting.upsert({
          where: { key: SETTINGS_KEY },
          create: { key: SETTINGS_KEY, encryptedValue: encryptCredential(JSON.stringify(next)), updatedById: request.staffUser!.sub },
          update: { encryptedValue: encryptCredential(JSON.stringify(next)), updatedById: request.staffUser!.sub },
        }),
        db.adminAuditLog.create({ data: { actorId: request.staffUser!.sub, action: "platform_integrations.updated", target: SETTINGS_KEY } }),
      ]);
      applyIntegrationSettings(next as IntegrationSettings);
      return reply.send(safe(next));
    },
  );
}
